import type { Metadata } from 'next';
import './lib/theme/globals.css';
import clsx from 'clsx';
import { TooltipProvider } from '@radix-ui/react-tooltip';
import {
	SF_Mono,
	SF_Pro,
	SF_Pro_Display,
	SF_Pro_Text,
} from './lib/theme/fonts';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang='en'
			className={clsx(
				SF_Pro_Display.variable,
				// SF_Pro_Text.variable,
				SF_Pro.variable,
				SF_Mono.variable,
			)}
		>
			<body className='font-sans text-base text-fg-1'>{children}</body>
		</html>
	);
}
